### ISSUE TITLE
Scene Parsing Failure! Exception:  dynamic module does not define module export function (PyInit_cv_bridge_boost)

### ISSUE THREAD

**Issue by jinHwanKim33** [vdorbala/LGX#1]
When I run **lgx-run.py** , 
the Error `Scene Parsing Failure! Exception:  dynamic module does not define module export function (PyInit_cv_bridge_boost)
` occurs. I will be happy if you give me a solution

**Comment by vdorbala** [comment]
This appears to be an issue with the OpenCV bridge for ROS with python3. Are you sure you built vision-opencv (refer the catkin workspace setup in instructions) in the catkin workspace? Also, make sure that your catkin workspace is properly sourced.

Follow the instructions here - [link](https://cyaninfinite.com/ros-cv-bridge-with-python-3/).
